apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  chart:
    spec:
      chart: goldilocks
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      version: 6.2.x
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  releaseName: goldilocks
  valuesFrom:
    - kind: ConfigMap
      name: goldilocks-values
