vpa:
  enabled: false
dashboard:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/secure-backends: "true"
    tls:
      - hosts:
          - goldilocks.quantu.app
        secretName: goldilocks-quantu-app-tls
    hosts:
      - host: goldilocks.quantu.app
        paths:
          - path: /
