apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: 3.8.x
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  releaseName: metrics-server
  valuesFrom:
    - kind: ConfigMap
      name: metrics-server-values
