apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.11.x
  interval: 1h0m0s
  releaseName: cert-manager
  values:
    installCRDs: true
    prometheus:
      enabled: false
    ingressShim:
      defaultIssuerName: letsencrypt
      defaultIssuerKind: ClusterIssuer

