apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: kube-public
spec:
  chart:
    spec:
      chart: goldilocks
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      version: 6.5.x
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  releaseName: goldilocks
  values:
    vpa:
      enabled: false
    dashboard:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/secure-backends: "true"
        hosts:
          - host: goldilocks.quantu.app
            paths:
              - path: /
                type: ImplementationSpecific
        tls:
          - hosts:
              - goldilocks.quantu.app
            secretName: goldilocks-quantu-app-tls

