apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - ingress-nginx.yaml
  - goldilocks.yaml
  - kubernetes-dashboard.yaml
  - metrics-server.yaml
  - sealed-secrets.yaml
  - vpa.yaml
