apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.9.x
  interval: 1h0m0s
  releaseName: cert-manager
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
