apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
spec:
  chart:
    spec:
      chart: vpa
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      version: 1.0.x
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  releaseName: vpa
